### ISSUE TITLE
Font Fallback

### ISSUE THREAD

**Issue by Aerodlyn** [mdylla/prj-rev-bwfs-dasmoto#2]
https://github.com/mdylla/prj-rev-bwfs-dasmoto/blob/ebdc6e2c7f558792f13669eb99a8b7a1d0c144d7/Dasmoto's%20Arts%20%26%20Crafts/resources/css/index.css#L2

When specifying a font for your website, it is typically a good idea to specify a fallback font (or family) so that if a visitor doesn't have that specific font, the look-and-feel of your site will remain consistent.

Specifying a fallback font can be done like so: `font-family: helvetica, sans-serif;`

**Comment by mdylla** [comment]
haven't seen this yet, but makes sense.
