### ISSUE TITLE
Code Reuse

### ISSUE THREAD

**Issue by Aerodlyn** [mdylla/prj-rev-bwfs-dasmoto#3]
https://github.com/mdylla/prj-rev-bwfs-dasmoto/blob/ebdc6e2c7f558792f13669eb99a8b7a1d0c144d7/Dasmoto's%20Arts%20%26%20Crafts/resources/css/index.css#L1-L7

https://github.com/mdylla/prj-rev-bwfs-dasmoto/blob/ebdc6e2c7f558792f13669eb99a8b7a1d0c144d7/Dasmoto's%20Arts%20%26%20Crafts/resources/css/index.css#L11-L16

When multiple tags, classes, and IDs use the same properties, you can condense your code a bit by specifying them all at the same time or by specifying those properties in a parent tag as children of tags inherit from their parents (e.g all tags inherit properties from `body` or `html`). You can specify the properties of multiple tags like so: `h1, h2, p, a { ... }`.

**Comment by mdylla** [comment]
Makes sense.  I did the project in blocks, but I'll keep in mind going forward.
