### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Aerodlyn** [mdylla/prj-rev-bwfs-dasmoto#4]
Overall, great job! You structured your code in a clear and concise way, and practiced good (HTML/CSS) typing habits, and I liked that you commented your HTML file. The only issues I saw with your code were relatively minor, which was choosing a font fallback and combining property definitions. These are more for user and developer experience, and using a font fallback will ensure that your site's look-and-feel will remain as consistent as possible for all users.

The left-to-right thing is simply that specifying the text direction may be unnecessary, but definitely doesn't hurt, and I appreciate that you commented your code!

Good job!

**Comment by mdylla** [comment]
Thanks for the feedback.  Very helpful.
